# Generated by Django 5.0.4 on 2024-05-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='subgrantgoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subgrantgoal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgrantgoal',
            name='grantgoal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.grantgoal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(default='Generic Activities', max_length=128),
        ),
        migrations.AlterField(
            model_name='goal',
            name='days_duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(default='Generic Goal description', max_length=128),
        ),
        migrations.AlterField(
            model_name='goal',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goalname',
            field=models.CharField(default='Generic Goal', max_length=64),
        ),
        migrations.AlterField(
            model_name='goal',
            name='state',
            field=models.CharField(choices=[('IN PROGRESS', 'IP'), ('DONE', 'DN'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='goal',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='days_duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='description',
            field=models.CharField(default='Generic Grant Goal description', max_length=128),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='state',
            field=models.CharField(choices=[('IN PROGRESS', 'IP'), ('DONE', 'DN'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='days_duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.CharField(default='Generic Issue description', max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issuename',
            field=models.CharField(default='Generic Issue', max_length=64),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('IN PROGRESS', 'IP'), ('DONE', 'DN'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='days_duration',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='description',
            field=models.CharField(default='Generic Sub Grant Goal description', max_length=128),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='final_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='state',
            field=models.CharField(choices=[('IN PROGRESS', 'IP'), ('DONE', 'DN'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
