# Generated by Django 5.0.4 on 2024-05-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal_subgrantgoal_issue_goal_subgrantgoal_grantgoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('IN PROGRESS', 'IP'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='grantgoal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('IN PROGRESS', 'IP'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='issue',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('IN PROGRESS', 'IP'), ('PENDING', 'PD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subgrantgoal',
            name='state',
            field=models.CharField(choices=[('DONE', 'DN'), ('IN PROGRESS', 'IP'), ('PENDING', 'PD')], max_length=16),
        ),
    ]
